mysite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
    re_path(r'^webpush/', include('webpush.urls'))
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.chat, name="chat"),
    path('createform/', views.createform, name='createform'),
    path('contact/', views.contact, name='contact'),
    path("signup", views.signup, name="signup"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("home", views.home, name="home"),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib import admin
import os
import openai
import requests
from django.contrib.auth import get_user_model
from webpush import send_user_notification, send_group_notification
from webpush.utils import send_to_subscription
import json
with open('./.env') as f:
    for line in f:
        key, value = line.strip().split('=')
        os.environ[key] = value
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
class Querys(models.Model):
    studentID = models.CharField(max_length=50)
    name = models.CharField(max_length=200)
    query = models.CharField(max_length=200)
    


def answer(query):
  openai.api_key = os.getenv("OPENAI_API_KEY")
  response = openai.ChatCompletion.create(
      model = "gpt-3.5-turbo",
      messages = [
          {"role": "system", "content": "Please answer the questions below in one line.\n"},
          {"role": "user", "content": query}
      ]
  )
  return response['choices'][0]['message']['content']



def get_translate(text, language):
    client_id = os.getenv("client_id")
    client_secret = os.getenv("client_secret")
    if language: a='ko'; b = "en"
    else: a='en'; b = "ko"
    data = {'text' : text,#inputtext
            'source' : a,#input lan
            'target': b}#output lan

    url = "https://openapi.naver.com/v1/papago/n2mt"

    header = {"X-Naver-Client-Id":client_id,
              "X-Naver-Client-Secret":client_secret}

    response = requests.post(url, headers=header, data= data)
    rescode = response.status_code

    if(rescode==200):
        t_data = response.json()
        return response.json()['message']['result']['translatedText']
    else:
        print("Error Code:" , rescode)
        return 0
    


def episode_webpush(episode):

    User = get_user_model()
    users = User.objects.all()

    payload = {"head": f"{episode.__str__()}이 업데이트 되었습니다.", "body": f"{episode.__str__()} 업데이트 일시 : {episode.modify_date}", 
            "icon": "https://i.imgur.com/...", "url": f"{episode.get_absolute_url()}"}
     
    payload = json.dumps(payload) # json으로 변환 https://github.com/safwanrahman/django-webpush/issues/71

    for user in users:
        push_infos = user.webpush_info.select_related("subscription") 

        for push_info in push_infos:
            send_to_subscription(push_info.subscription, payload)

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect, QueryDict
from django.template import loader
from .models import Question, Choice, Querys, answer, get_translate, episode_webpush
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core.mail import send_mail, EmailMessage
from django.template.loader import render_to_string
from webpush import send_user_notification
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth import authenticate

def createform(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        form = QueryDict('', mutable=True)
        form.update(request.POST)
        # form['query'] = get_translate(answer(get_translate(form["name"], True)), False)
        form['query'] = "TEST"
        send_mail(
            form["name"],
            form['query'],
            "django2633@gmail.com",
            ["secrett2633@kakao.com"],
            fail_silently=False,
        )
        payload = {"head": form["name"], "body": form['query']}
        user = request.user #secrett
        send_user_notification(user=user, payload=payload, ttl=1000)
        
        # query = Querys()
        # query.studentID = request.POST.get('studentID')
        # query.name = request.POST.get('name')
        # query.query = "test"
        # query.save()
    try:
        return render(request, "polls/index.html", {"form": form["query"]})
    except:
        return render(request, "polls/index.html")

def contact(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        send_mail(
            request.POST.get('email') + "님이 보낸 메일입니다.",
            request.POST.get('content'),
            "django2633@gmail.com",
            ["secrett2633@kakao.com"],
            fail_silently=False,
        )
        
        send_mail(
            "[ChatBot] 성공적으로 문의가 등록되었습니다.",
            '''당사 서비스에 관심을 가지고 시간을 내어 문의해 주셔서 감사합니다.
            더 나은 지원을 위해 귀하의 질문에 대한 자세한 정보를 제공해 주시겠습니까? 
            이것은 귀하의 요구 사항을 이해하고 가장 적절한 솔루션을 제공하는 데 도움이 될 것입니다.
            추가 질문이나 우려 사항이 있는 경우 주저하지 말고 문의해 주십시오. 
            우리는 항상 당신을 돕기 위해 있습니다.
            양해해 주셔서 감사합니다.''',
            "django2633@gmail.com",
            [request.POST.get('email'), "secrett2633@kakao.com"],
            fail_silently=False,
        )
    try:
        name = request.session['name']
    except:
        name = "질문을 입력해주세요"
    return render(request, "polls/chat.html", {"name" : name})

def chat(request):    
    if request.method == "POST":
        request.session["name"] = request.POST.get('quest')
        now = get_translate(request.session["name"], True)
        print(now)
        now = answer(now)
        print(now)
        now = get_translate(now, True)
        print(now)
        form = [[request.session["name"], now]]        
        # form = [[request.session["name"], "NONE"]]        
        if "form" not in request.session: 
            request.session["form"] = form            
        else: 
            request.session["form"] += form
        return render(request, "polls/chat.html", {"question": request.session['form'], "name" : request.session['name']})
    try:
        name = request.session['name']
    except:
        name = "질문을 입력해주세요"
    return render(request, "polls/chat.html", {"name" : name})

def signup(request):
    try:
        name = request.session['name']
    except:
        name = "질문을 입력해주세요"
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password1'],
                email=request.POST['email'],)
            auth.login(request, user)
            return render(request, "polls/chat.html", {"name" : name})
        return render(request, "polls/chat.html", {"name" : name})
    return render(request, "polls/chat.html", {"name" : name})
def login(request):
    try:
        name = request.session['name']
    except:
        name = "질문을 입력해주세요"
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return render(request, "polls/chat.html", {"name" : name})
        else:
            return render(request, "polls/chat.html", {"name" : name})
    else:
        return render(request, "polls/chat.html", {"name" : name})


# 로그아웃
def logout(request):
    try:
        name = request.session['name']
    except:
        name = "질문을 입력해주세요"
    auth.logout(request)
    return render(request, "polls/chat.html", {"name" : name})

# home
def home(request):
    return render(request, 'polls/home.html')

# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     context = {"latest_question_list": latest_question_list}
#     return render(request, "polls/index.html", context)

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/detail.html", {"question": question})


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, "polls/results.html", {"question": question})


# class IndexView(generic.ListView):
#     template_name = "polls/index.html"
#     context_object_name = "latest_question_list"

#     def get_queryset(self):
#         """
#         Return the last five published questions (not including those set to be
#         published in the future).
#         """
#         return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
#             :5
#         ]


# class DetailView(generic.DetailView):
#     def get_queryset(self):
#         """
#         Excludes any questions that aren't published yet.
#         """
#         return Question.objects.filter(pub_date__lte=timezone.now())
    
#     model = Question
#     template_name = "polls/detail.html"


# class ResultsView(generic.DetailView):
#     model = Question
#     template_name = "polls/results.html"

# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST["choice"])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(
#             request,
#             "polls/detail.html",
#             {
#                 "question": question,
#                 "error_message": "You didn't select a choice.",
#             },
#         )
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

polls/templates/polls/chat.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<body>
<div class="modal">
	<div class="modal_body">
		<div style="text-align: center;">
			<h1>로그인</h1>
			<form action="{% url 'polls:login' %}" method="POST">
				{% csrf_token %}
				<input name="username" type="text" placeholder = "아이디"><br>
				<input name="password" type="password" placeholder = "비밀번호"><br>
				<input type="submit" class="btn btn-primary" value="로그인">
			</form>
		</div>
	</div>	
</div>	
<div class="modal1">
	<div class="modal1_body">
		<div style="text-align: center;">
			<h1>회원가입</h1>
			<form action="{% url 'polls:signup' %}" method="POST">
				{% csrf_token %}
				<input name="email" type="email" placeholder = "이메일"><br>
				<input name="username" type="text" placeholder = "아이디"><br>
				<input name="password1" type="password" placeholder = "비밀번호"><br>
				<input name="password2" type="password" placeholder = "비밀번호확인"><br>
				<input type="submit" class="btn btn-primary" value="회원가입">
			</form>
		</div>
	</div>	
</div>
<div class="modal2">
	<div class="modal2_body">
		<div style="text-align: center;">
			<h1>문의하기</h1>
			<form action="{% url 'polls:contact' %}" method="POST">
				{% csrf_token %}
				<input name="email" type="email" placeholder = "이메일"><br>
				<input name="content" type="text" placeholder = "문의내용"><br>
				<input type="submit" class="btn btn-primary" value="제출">
			</form>
		</div>
	</div>	
</div>
<div id="container">	
	<aside>
		<header> <input type="text" placeholder="search"> </header>
		<ul> 
			<li class="qu">
				<div> <h2>{{ name }}</h2> </div> 
			</li>
		</ul>
		<ul>
			<li class="btn2-open-popup">
				<div> <h2 class="btn2-open-popup auth">문의하기</h2> </div>
			</li>
			<li class="btn1-open-popup">
				{% if user.is_authenticated %}
				<img><div></div>
				{% else %}
				<div> <h2 class="btn1-open-popup auth">회원가입</h2> </div>
				{% endif %}				
			</li>				
			<li class="btn-open-popup">
				{% if user.is_authenticated %}
				<div> <h2 href="{% url 'polls:logout' %}" class = "auth">로그아웃</h2> </div>
				{% else %}
				<div> <h2 class="btn-open-popup auth">로그인</h2> </div>
				{% endif %}				
			</li>				
		</ul>
	</aside>
	<main>
		<ul id="chat">
			{% if question %}
				{% for a, b in question %}
				<li class="me">
					<div class="entete"> <h2>나</h2> </div>
					<div class="message"> {{ a }} </div>
				</li>
				<li class="you">
					<div class="entete"> <h2>Turbo</h2> </div> 
					<div class="message"> {{ b }} </div>
				</li>		
				{% endfor %}
			{% endif %}
		</ul>
		<footer>			
			<form action="{% url 'polls:chat' %}" method="POST">
			{% csrf_token %}
			<input placeholder="질문을 입력해주세요!" id="my-textarea" name="quest"></input>   
			</form>
		</footer>
	</main>
</div>

<script src="{% static 'polls/chat.js' %}"></script>

</body>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

polls/templates/polls/home.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<link rel="stylesheet" href="{% static 'polls/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'polls/login-register.css' %}">
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome//4.0.3/css/font-awesome.css"> 
<script src="{% static 'polls/jquery-1.10.2.js' %}"></script>
<script src="{% static 'polls/bootstrap.js' %}"></script>
<script src="{% static 'polls/login-register.js' %}"></script>
<div>
    <h3><a href="accounts">회원가입</a></h3>
    <h3><a href="login">로그인</a></h3>
    <h3><a href="logout">로그아웃</a></h3>
</div>
<div class="container">
  <div class="row">
      <div class="col-sm-4"></div>
      <div class="col-sm-4">
           <a class="btn big-login" data-toggle="modal" href="javascript:void(0)" onclick="openLoginModal();">Log in</a>
           <a class="btn big-register" data-toggle="modal" href="javascript:void(0)" onclick="openRegisterModal();">Register</a></div>
      <div class="col-sm-4"></div>
  </div>


  
</div>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

<form action="{% url 'polls:createform' %}" method="POST">
{% csrf_token %}
<div>
    <label for="studentID">입력</label>
    <input type="text" name="studentID" id="studentID">
</div>
<div>
    <label for="name">출력</label>
    <input type="text" name="name" id="name">
</div>
<br>
<input type="submit" value="제출">
</form>

{% if form %}
    <h1> {{ form }}</h1>
{% endif %}

{% load webpush_notifications %}
{% webpush_header %}
{% webpush_button %}

polls/templates/polls/login.html
<div class="wrapper">
    <div style="text-align: center;">
        <h1>로그인</h1>
        <form method="POST">
            {% csrf_token %}
            아이디:
            <br>
            <input name="username" type="text">
            <br>
            비밀번호:
            <br>
            <input name="password" type="password">
            <br><br>
            <input type="submit" class="btn btn-primary" value="Login">
        </form>
    </div>
</div>

polls/templates/polls/name.html
<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

polls/templates/polls/push.html
{% load webpush_notifications %}
<head>
# For django templating engine
{% webpush_header %}
# For jinja templating engine
</head>
<body>
<p> Hello World! </p>
# For django templating engine
{% webpush_button %}
# For jinja templating engine
</body>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

<form id="logout-form" method="post" action="{% url 'admin:logout' %}">
    {% csrf_token %}
    <button type="submit">{% translate 'Log out' %}</button>
</form>

polls/templates/polls/signup.html
{% block content %}
<div class="wrapper" style="text-align: center;">
    <h1>회원가입</h1>
    <form method="POST">
        {% csrf_token %}
        아이디: <br>
        <input name="username" type="text">
        <br>
        비밀번호: <br>
        <input name="password1" type="password">
        <br>
        비밀번호 확인: <br>
        <input name="password2" type="password">
        <br>
        이메일: <br>
        <input name="email" type="email">
        <br><br>
        <input type="submit" class="btn btn-primary" value="Sign Up">
    </form>
</div>
{% endblock %}